package io.github.lunaiskey.pyrexprison.gui;

public enum PyrexInvType {
    PMINE_MAIN,
    PMINE_BLOCKS,
    PMINE_UPGRADES,
    PMINE_PUBLIC_MINES,
    PMINE_SETTINGS,
    PICKAXE_ENCHANTS,
    PICKAXE_ENCHANTS_ADD_LEVELS,
    PICKAXE_ENCHANTS_TOGGLE,
    PERSONAL_BOOSTER,
    ARMOR,
    ARMOR_UPGRADES,
    GEMSTONES,
    VIEW_PLAYER,
    PLAYER_MENU,
    ;

}
